:toc: right
:toclevels: 4

== Spinnaker for Cloud Foundry

WARNING: Spinnaker for Cloud Foundry and Spinnaker on Cloud Foundry is at an alpha stage. We have a proof of concept, not something ready for production. Before showing to any customers, it's best if you experiment with it first and understand what it does and doesn't do. You've been warned.

Spinnaker has built-in support for Cloud Foundry

* You can run all the parts on Cloud Foundry
* Cloud Foundry can be the target of deployments
* Cloud Foundry's enterprise version of Jenkins can be the trigger for Spinnaker pipelines

This document is a starting point if you want to either use or develop in these configurations.

=== Developing Spinnaker for CF

Want to work on Spinnaker's Cloud Foundry features? Here are the key steps you'll need to get it up and running on your local machine.

==== Step 0 

To work on Cloud Foundry, you need:

* JDK 8
* working knowledge of Spring MVC, Spring Boot, and Groovy
* a suitable IDE (IntelliJ, Spring Tool Suite with Groovy support, Sublime Text, ...)

==== Checking out and running the code

. Clone the following repositories:
+
----
git clone git@github.com:spinnaker/clouddriver.git
git clone git@github.com:spinnaker/deck.git
git clone git@github.com:spinnaker/echo.git
git clone git@github.com:spinnaker/front50.git
git clone git@github.com:spinnaker/gate.git
git clone git@github.com:spinnaker/igor.git
git clone git@github.com:spinnaker/orca.git
----
+
. Clone this configuration => `git clone git@github.com:gregturn/spinnaker-config.git`
. Make any edits you need to `/path/to/spinnaker-config/spinnaker-local.yml` to plugin custom PCF/PWS details, etc.
. Open a separate shell for each of these repositories, and `cd` into them.
. Run echo, front50, gate, igor, and orca by typing the following in each shell => `./gradlew clean bootRun -Dspring.config.location=/path/to/spinnaker-config/` (<-- need trailing '/')
. Run clouddriver with your CF credentials by typing => `CF_ACCOUNT_NAME=<your userid> CF_ACCOUNT_PASSWORD=<your password> ./gradlew clean bootRun -Dspring.config.location=/path/to/spinnaker-config/`
. In deck, copy in the cf settings by typing => `cp /path/to/spinnaker-config/settings.js /path/to/deck/settings.js`
. Install deck bits with `npm install`
. Run deck by typing => `API_HOST=http://localhost:8084 npm start`
. Visit http://localhost:9000/webpack-dev-server/

==== Services

Spinnaker uses not only the preceding modules, but redis and cassandra. To run Spinnaker, you need to install these as well.

===== Redis

If you are using a Mac, you can install redis via homebrew:

----
$ brew install redis
$ redis-server
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 3.0.4 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 52305
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

52305:M 10 Nov 11:38:13.563 # Server started, Redis version 3.0.4
----

Now you have a local redis server up and running.

===== Jenkins

You can install p-jenkins in your cloud environment. It requires going to CloudBees and requesting a license (which I did, and managed to get a freebie). But if you're running in a local environment, you can probably get by using the https://jenkins-ci.org/[OSS version].

Got Docker? It might be even easier to run it that way. (I don't know, you tell me!)

If you need to trigger pipelines, you will want to set this up at some point.

=== Running Spinnaker on Cloud Foundry

Want to use Spinnaker in a Cloud Foundry environment? Here are the steps to build and push to your CF environment.

First and foremost, you have to build each module as a uber JAR. Then you have to tell each module where to get it's designated property files.

IMPORTANT: When using local file paths, you can simply point to the directory. To reference remote files on github, you have specify each file, separated by ",".

clouddriver:

. `./gradlew -DspringBoot.repackage=true clean build`
. `cf push clouddriver -p clouddriver-web/build/libs/clouddriver-web-<version>.jar`
. `cf set-env clouddriver CF_ACCOUNT_NAME <your CF email>`
. `cf set-env clouddriver CF_ACCOUNT_PASSWORD <your CF password>`
. `cf set-env clouddriver SPRING_CONFIG_LOCATION https://raw.githubusercontent.com/gregturn/spinnaker-config/master/spinnaker.yml,https://raw.githubusercontent.com/gregturn/spinnaker-config/master/spinnaker-local.yml,https://raw.githubusercontent.com/gregturn/spinnaker-config/master/clouddriver.yml,https://raw.githubusercontent.com/gregturn/spinnaker-config/master/clouddriver-local.yml`

echo:

. `./gradlew clean build`
. `cf push echo -p echo-web/build/libs/echo-web-<version>.jar`
. `cf set-env echo SPRING_CONFIG_LOCATION https://raw.githubusercontent.com/gregturn/spinnaker-config/master/spinnaker.yml,https://raw.githubusercontent.com/gregturn/spinnaker-config/master/spinnaker-local.yml,https://raw.githubusercontent.com/gregturn/spinnaker-config/master/echo.yml,https://raw.githubusercontent.com/gregturn/spinnaker-config/master/echo-local.yml`

front50:

. `./gradlew clean build`
. `cf push front50 -p front50-web/build/libs/front50-web-<version>.jar`
. `cf set-env front50 SPRING_CLOUD_CONFIG_ENABLED true`
. `cf set-env front50 SPRING_CLOUD_CONFIG_URI http://gate.white.springapps.io/config`

gate:

> **NOTE**: Pending https://github.com/spinnaker/gate/pull/187 to build uber jars

. `./gradlew clean buildDeb`
. `cf push gate -p gate-web/build/install/gate/`
. `cf set-env gate SPRING_CLOUD_CONFIG_SERVER_BOOTSTRAP true`
. `cf set-env gate SPRING_CLOUD_CONFIG_SERVER_ENABLED true`
. `cf set-env gate SPRING_CLOUD_CONFIG_SERVER_GIT_URI https://github.com/gregturn/spinnaker-config/`

igor:

. `./gradlew -DspringBoot.repackage=true clean build`
. `cf push igor -p igor-web/build/libs/igor-web-<version>.jar`
. `cf set-env orca SPRING_CONFIG_LOCATION https://raw.githubusercontent.com/gregturn/spinnaker-config/master/spinnaker.yml,https://raw.githubusercontent.com/gregturn/spinnaker-config/master/spinnaker-local.yml,https://raw.githubusercontent.com/gregturn/spinnaker-config/master/igor.yml,https://raw.githubusercontent.com/gregturn/spinnaker-config/master/igor-local.yml`

orca:

. `./gradlew clean build`
. `cf push orca -p orca-web/build/libs/orca-web-<version>.jar`
. `cf set-env orca SPRING_CONFIG_LOCATION https://raw.githubusercontent.com/gregturn/spinnaker-config/master/spinnaker.yml,https://raw.githubusercontent.com/gregturn/spinnaker-config/master/spinnaker-local.yml,https://raw.githubusercontent.com/gregturn/spinnaker-config/master/orca.yml,https://raw.githubusercontent.com/gregturn/spinnaker-config/master/orca-local.yml`

deck:

. `./gradlew clean build -x test`
. `cf push deck -p build/webpack/ -b staticfile_buildpack`

WARNING: Running deck with the static buildpack will NOT read environment variables in production. You MUST put the proper gate URL and protocol in settings.js as the default values.

Pushing out new copies of software does not require that set the environment variables again. That only has to happen once.

=== Cloudbees Enterprise Jenkins

If you are running Pivotal Cloud Foundry with https://network.pivotal.io/products/cloudbees[CloudBees Jenkins Enterprise], you can configure your build jobs there. Upon doing so, TBD...

== Issues

Got problems? Check these channels for help and guidance:

* File https://github.com/spinnaker/spinnaker/issues[detailed issues] with this repository, unless you know the specific module that is failing. HINT: A failure in one module could be sourced in another.
* Check in on the spinnaker slack chat channel. Visit #dev if you are developing spinnaker and #user if you are interacting with a running instance.
* Post questions at http://stackoverflow.com/questions/tagged/spinnaker[stackoverflow underneath the "spinnaker" tag].
