:toc: right
:toclevels: 4

== Spinnaker for Cloud Foundry

WARNING: Spinnaker for Cloud Foundry and Spinnaker on Cloud Foundry is at an alpha stage. We have a proof of concept, not something ready for production. Before showing to any customers, it's best if you experiment with it first and understand what it does and doesn't do. You've been warned.

Spinnaker has built-in support for Cloud Foundry

* You can run all the parts on Cloud Foundry
* Cloud Foundry can be the target of deployments
* Cloud Foundry's enterprise version of Jenkins can be the trigger for Spinnaker pipelines

This document is a starting point if you want to either use or develop in these configurations.

=== Developing Spinnaker for CF

Want to work on Spinnaker's Cloud Foundry features? Here are the key steps you'll need to get it up and running on your local machine.

==== Step 0 

To work on Cloud Foundry, you need:

* JDK 8
* working knowledge of Spring MVC, Spring Boot, and Groovy
* a suitable IDE (IntelliJ, Spring Tool Suite with Groovy support, Sublime Text, ...)

==== Checking out and running the code

. Clone the following repositories:
+
----
git clone git@github.com:spinnaker/clouddriver.git
git clone git@github.com:spinnaker/deck.git
git clone git@github.com:spinnaker/echo.git
git clone git@github.com:spinnaker/front50.git
git clone git@github.com:spinnaker/gate.git
git clone git@github.com:spinnaker/igor.git
git clone git@github.com:spinnaker/orca.git
----
+
. Clone this configuration => `git clone git@github.com:gregturn/spinnaker-config.git`
. Make any edits you need to `/path/to/spinnaker-config/spinnaker-local.yml` to plugin custom PCF/PWS details, etc.
. Open a separate shell for each of these repositories, and `cd` into them.
. Run echo, front50, gate, igor, and orca by typing the following in each shell => `./gradlew clean bootRun -Dspring.config.location=/path/to/spinnaker-config/` (<-- need trailing '/')
. Run clouddriver with your CF credentials by typing => `CF_ACCOUNT_USER=<your userid> CF_ACCOUNT_PASSWORD=<your password> ./gradlew clean bootRun -Dspring.config.location=/path/to/spinnaker-config/`
. In deck, copy in the cf settings by typing => `cp /path/to/spinnaker-config/settings.js /path/to/deck/settings.js`
. Run deck by typing => `API_HOST=http://localhost:8084 npm start`
. Visit http://localhost:9000/webpack-dev-server/

==== Services

Spinnaker uses not only the preceding modules, but redis and cassandra. To run Spinnaker, you need to install these as well.

===== Redis

If you are using a Mac, you can install redis via homebrew:

----
$ brew install redis
$ redis-server
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 3.0.4 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 52305
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

52305:M 10 Nov 11:38:13.563 # Server started, Redis version 3.0.4
----

Now you have a local redis server up and running.

===== Cassandra

Spinnaker uses Apache Cassandra 1.2, which is not the default homebrew formula. To do this, you need to install version support:

----
$ brew update
$ brew tap homebrew/versions
$ brew install cassandra12
$ cassandra
----

This launches cassandra for local development work, but you aren't done. With a standalone cassandra instance, you have to load the keyspaces with a https://github.com/spinnaker/spinnaker/tree/master/cassandra[set of scripts]. This is analogous to loading a database schema.

WARNING: To run Spinnaker locally, you need standalone cassandra. Otherwise, the two services will collide if they try to run embedded instances separately on the same default port. However, when deploying to Pivotal Cloud Foundry, p-cassandra supplies cassandra 2.0 and doesn't work. In that situation, you need embedded cassandra, which pre-loades the keyspaces. This is covered in the configuration settings mentioned earlier.

This will spin up all the parts of Spinnaker needed to work with stuff. To develop any one module, shut down the copy in its shell, and instead open it up inside your IDE. Find the `Main` class and run it with the same environmental overrides.

===== Jenkins

You can install p-jenkins in your cloud environment. It requires going to CloudBees and requesting a license (which I did, and managed to get a freebie). But if you're running in a local environment, you can probably get by using the https://jenkins-ci.org/[OSS version].

Got Docker? It might be even easier to run it that way. (I don't know, you tell me!)

If you need to trigger pipelines, you will want to set this up at some point.

=== Running Spinnaker on Cloud Foundry

Want to use Spinnaker in a Cloud Foundry environment? Here are the steps to build and push to your CF environment.

First and foremost, you need Spring Cloud Config Server. The alternative will keep you up all night configuring individual property files.

To do so, you need to visit each repo clone you created up above and do this:

----
$ cd clouddriver
$ git remote add gregturn git@github.com:gregturn/clouddriver.git
$ git fetch gregturn
$ git checkout spring-cloud
----

Each of the modules above (except decK) has a spring-cloud branch. Repeat similar steps (swapping out `clouddriver` with the actual project) and then build that branch.

Once you have done that, you can start pushing things to PCF as shown below:

clouddriver:

. `./gradlew clean buildDeb`
. `cf push clouddriver -p clouddriver-web/build/install/clouddriver`
. `cf set-env clouddriver CF_ACCOUNT_NAME <your CF email>`
. `cf set-env clouddriver CF_ACCOUNT_PASSWORD <your CF password>`
. `cf set-env clouddriver SPRING_CLOUD_CONFIG_ENABLED true`
. `cf set-env clouddriver SPRING_CLOUD_CONFIG_URI http://gate.white.springapps.io/config`

echo:

. `./gradlew clean buildDeb`
. `cf push gate -p echo-web/build/install/gate/`
. `cf set-env echo SPRING_CLOUD_CONFIG_ENABLED true`
. `cf set-env echo SPRING_CLOUD_CONFIG_URI http://gate.white.springapps.io/config`

front50:

. `./gradlew clean buildDeb`
. `cf push gate -p front50-web/build/install/gate/`
. `cf set-env front50 SPRING_CLOUD_CONFIG_ENABLED true`
. `cf set-env front50 SPRING_CLOUD_CONFIG_URI http://gate.white.springapps.io/config`

gate:

. `./gradlew clean buildDeb`
. `cf push gate -p gate-web/build/install/gate/`
. `cf set-env gate SPRING_CLOUD_CONFIG_SERVER_BOOTSTRAP true`
. `cf set-env gate SPRING_CLOUD_CONFIG_SERVER_ENABLED true`
. `cf set-env gate SPRING_CLOUD_CONFIG_SERVER_GIT_URI https://github.com/gregturn/spinnaker-config/`

igor:

. `./gradlew clean buildDeb`
. `cf push igor -p igor-web/build/install/gate/`
. `cf set-env igor SPRING_CLOUD_CONFIG_ENABLED true`
. `cf set-env igor SPRING_CLOUD_CONFIG_URI http://gate.white.springapps.io/config`

orca:

. `./gradlew clean buildDeb`
. `cf push orca -p orca-web/build/install/gate/`
. `cf set-env igor SPRING_CLOUD_CONFIG_ENABLED true`
. `cf set-env igor SPRING_CLOUD_CONFIG_URI http://gate.white.springapps.io/config`

deck:

. `./gradlew clean build -x test`
. `cf push deck -p build/webpack/ -b staticfile_buildpack`

WARNING: Running deck with the static buildpack will NOT read environment variables in production. You MUST put the proper gate URL and protocol in settings.js as the default values.

Pushing out new copies of software does not require that set the environment variables again. That only has to happen once.

=== Cloudbees Enterprise Jenkins

If you are running Pivotal Cloud Foundry with https://network.pivotal.io/products/cloudbees[CloudBees Jenkins Enterprise], you can configure your build jobs there. Upon doing so, TBD...

== Issues

Got problems? Check these channels for help and guidance:

* File https://github.com/spinnaker/spinnaker/issues[detailed issues] with this repository, unless you know the specific module that is failing. HINT: A failure in one module could be sourced in another.
* Check in on the spinnaker slack chat channel. Visit #dev if you are developing spinnaker and #user if you are interacting with a running instance.
* Post questions at http://stackoverflow.com/questions/tagged/spinnaker[stackoverflow underneath the "spinnaker" tag].
