server:
  port: 8085

netflix:
  appinfo:
    name: 'igor'

jenkins:
  masters:
    -
      name: jenkins1
      address: http://jenkins-0.white.springapps.io/job/spinnaker
      username: 'admin'
      password: '7c9197dc00c378fb2ef5bc1d79a4b220'

services:
  echo:
    baseUrl: http://echo. white.springapps.io
spinnaker:
  build:
    pollInterval: 30

endpoints:
  health:
    sensitive: false

logging:
  level:
    retrofit: DEBUG
